### ISSUE TITLE
Reihung der Termine/Neuigkeiten

### ISSUE THREAD

**Issue by manuel88** [fetsite/fetsite#201]
Die Reihung der Termine ist etwas willkürlich, zb ist jetzt der TU Ball vor den Glühweintagen obwohl diese früher sind.
Es sollte ev auch eine Priorität gesetzt werden können für wichtige Neuigkeiten, die ganz oben angezegt werden sollen, wie Sitzungen etc

**Comment by manuel88** [comment]
Termine, die schon vorbei sind sollten nicht mehr auf der Hauptseite angezeigt werden bzw man könnte eine Funktion machen, von wann bis wann die Neuigkeit auf der Hauptseite angezeigt werden soll. Außerdem werden gerade eine willkürliche Anzahl (7 ausgeloggt, 10 eingeloggt) auf der Hauptseite angezeigt und es fehlt ein Button für "weitere Neuigkeiten"

**Comment by manuel88** [comment]
btw: geht die FB veröffentlichung schon?
es sollte beim Erstellen angezeigt werden, dass es noch nicht veröffentlicht wurde (ählich Entwurf gelb oder rot hinterlegen)

**Comment by manuel88** [comment]
Finde auch nicht sinnvoll öffentlich anzuzeigen, wer das Event erstellt hat

**Comment by andreassteph** [comment]
es gibt jetzt mal eine neue Reihung
