### ISSUE TITLE
Slideshow bei Fotos: javascript lädt nicht auf fet.at

### ISSUE THREAD

**Issue by manuel88** [fetsite/fetsite#228]
Find ich wichtiger als Downloadbutton

**Comment by Inachos** [comment]
Ich auch, deswegen hab ichs in  #215 gefixt. 
Ich weiß nicht warum es auf der fetsite ned, anscheinend wir das javascript ned ausgeführt

**Comment by andreassteph** [comment]
hat an fehlendem precompile im production modus gelegen --> gefixed
