### ISSUE TITLE
Interne Ankündigungen mühsam

### ISSUE THREAD

**Issue by manuel88** [fetsite/fetsite#245]
zb FakRat: create meeting -> ankündigen ->neuigkeiten-> offizielles Intern ->Termin auswählen -> action -> veröffentlichen -> OK

warum nicht gleich termin+meeting veröffentlichen, sind sowiso intern?

**Comment by andreassteph** [comment]
In der Tat zu viele Clicks.

Am 18. März 2015 um 19:26 schrieb manuel88 <notifications@github.com>:
