### ISSUE TITLE
Uploadfunktion auf allen Seiten

### ISSUE THREAD

**Issue by manuel88** [fetsite/fetsite#248]
sinnvoll für Fetzn, anmerkungen zu Protokollen...

**Comment by manuel88** [comment]
Again
will was in Fakultätsratsitzungen und Biomedical Engineering uploaden

**Comment by andreassteph** [comment]
Hab mal bei einigen objekten attachments hinzugefügt. Schließe mal den punkt falls noch irgendwo sinnvoll bitte einfach noch mal schreiben
